name: ordermanager
description: A handy order management and pocket selling app. 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.2.2
  url_launcher: ^6.0.7
  fluttertoast: ^8.0.7
  printing: ^5.4.2
  pdf: ^3.4.2
  flutter_html_to_pdf: ^0.6.1
  path_provider: ^2.0.2
  flutter_launcher_icons: ^0.9.0
  flutter_secure_storage: ^4.2.0
  date_format: ^2.0.2
  confirm_dialog: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter_icons:
    android: true
    ios: true
    image_path: "images/logo.png"
    image_path_ios: "images/logo.png"
    image_path_android: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
          style: italic